theme: jekyll-theme-dinky

#theme: jekyll-theme-minimal

title: [CRISPR Screening Cancer]
description: [This is an accompanied website to allow browsing the results from the paper...]

# show_downloads: ["true" or "false" to indicate whether to provide a download URL]
show_downloads: ["true"]
# google_analytics: [Your Google Analytics tracking ID]
